# Syntax-check Travis YAML .travis.yml files at http://lint.travis-ci.org

language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libnetcdf6 libnetcdf-dev netcdf-bin udunits-bin libudunits2-0 libudunits2-dev
  - ./configure
  - export DATA='/home/travis'

script:
  - make -j 4
  - make test
